name: mod_disco
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #  flutter_localizations:
  #    sdk: flutter

  responsive_builder: ^0.3.0
  #  responsive_scaffold: ^1.3.0+2
  #  floating_search_bar: ^0.3.0
  # protobuf: ^1.0.1
  provider: ^4.3.2+3
  provider_architecture: ^1.0.6
  path_provider: ^1.6.7
  #  equatable:
  meta:
  flutter_modular: ^3.0.0-0
  intl: ^0.17.0-nullsafety.2
  #  intl_translation: ^0.17.10+1
  data_tables: ^1.0.3
  random_string: ^2.2.0-0
  flutter_platform_widgets: ^1.0.0-nullsafety.0
  cupertino_icons: ^1.0.0
  #  font_awesome_flutter: ^8.7.0
  #  flutter_material_pickers: ^1.8.1
  grpc: ^2.8.0
  protobuf: ^1.1.0
  youtube_player_iframe: ^1.1.0
  carousel_slider: ^2.3.1
  #  sys_core:
  #    git:
  #      url: git://github.com/amplify-cms/sys-share
  #      path: sys-core/service/flu
  sys_share_sys_account_service:
    #    git:
    #      url: git://github.com/amplify-cms/sys-share.git
    #      path: sys-account/service/flu
    #      ref: 35b645d047ee71de41a99f17d8670b9bbeffd95c
    path: ../../../../sys-share/sys-account/service/flu
  # mod_timespace:
  #   path: ../../mod-timespace/client

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.2
  hive_generator: ^0.8.2
  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.8.1
  intl_translation:
    git:
      url: https://github.com/gutterbacon/intl_translation
      ref: 248adfbd76ad3d3be702fb376cfa28112fa1a5b4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ./i18n/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
